# Generated by Django 5.2.13 on 2026-04-15 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='main.task', verbose_name='Задача'),
        ),
    ]
