# Generated by Django 5.2.13 on 2026-04-19 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_submission_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Оригинальное имя файла')),
                ('file', models.FileField(upload_to='signed_docs/%Y/%m/%d/', verbose_name='Файл')),
                ('signature', models.FileField(upload_to='signatures/%Y/%m/%d/', verbose_name='Подпись')),
                ('file_hash', models.CharField(max_length=64, verbose_name='Хеш файла (SHA-256)')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='Время подписания')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Проверена ли подпись')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signed_documents', to=settings.AUTH_USER_MODEL, verbose_name='Подписавший')),
            ],
            options={
                'verbose_name': 'Подписанный документ',
                'verbose_name_plural': 'Подписанные документы',
                'ordering': ['-signed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.TextField(verbose_name='Открытый ключ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ключи пользователя',
                'verbose_name_plural': 'Ключи пользователей',
            },
        ),
    ]
